"""
Agent layer: routes a natural-language ops question to the deterministic
skills in skills.py (tool use), then has Claude turn the raw hits into a
decision-ready answer that cites which source system each number came from.

This is the "AI agent that replaces the hire" demo: the numbers are never
generated by the model — they come from skills.py's pandas joins over the
custodian + portfolio-accounting exports. Claude's job is routing (which
skill, what threshold) and writing the final report.
"""

import json
from typing import Literal

import anthropic
from anthropic import beta_tool
from pydantic import BaseModel, Field

from skills import tlh_scan, concentration_scan, wash_sale_scan

MODEL = "claude-opus-5"


class ChartSpec(BaseModel):
    """A chart specification the model derives from the *actual* scan result,
    not a hardcoded template per tool -- so a new skill with a different data
    shape still gets a sensible chart without any UI code changes."""

    should_chart: bool = Field(
        description="False if the data doesn't support a meaningful chart "
        "(e.g. empty results, or a single scalar with nothing to compare)."
    )
    chart_type: Literal["bar"] = Field(
        description="Chart form. Only 'bar' is supported today -- use it for "
        "ranking/comparing a magnitude across categories."
    )
    title: str = Field(description="Short chart title, e.g. 'Concentration risk by position'.")
    label_fields: list[str] = Field(
        description="Field name(s) from each data row to join (with ' · ') into "
        "the category label for that bar -- pick whichever fields make each row "
        "uniquely identifiable, e.g. ['symbol', 'household']."
    )
    value_field: str = Field(
        description="Field name from each data row holding the numeric magnitude to plot."
    )
    value_format: Literal["percent", "currency", "number"] = Field(
        description="How to display each value: 'percent' -> '12.3%', "
        "'currency' -> '$12,300', 'number' -> '12,300'."
    )
    value_axis_title: str = Field(description="Axis title for the value, e.g. 'Unrealized loss (%)'.")
    use_absolute_value: bool = Field(
        description="True if value_field can be negative (e.g. a loss) and the "
        "chart should plot magnitude rather than sign."
    )

SYSTEM_PROMPT = """\
You are an operations analyst agent for a wealth management firm. You answer \
advisor and compliance questions about the firm's book of business by calling \
the tools available to you -- never estimate or invent a number yourself.

Rules:
- Always call a tool to get the underlying data before answering. Never answer \
from general knowledge.
- When you report a number, cite the "source" field from the tool result so the \
reader knows which system it came from (this is the whole point: the answer must \
be traceable back to custodian data / portfolio accounting data, not "the AI said so").
- Write the final answer as a short, decision-ready report: a one-line summary, \
then a compact list of the specific accounts/households/positions involved. Do \
not just dump raw JSON.
- If a scan returns no hits, say so plainly rather than inventing a result.
"""


# Side channel: the last tool call's raw structured result, so the UI layer
# can chart it directly instead of re-running the scan or parsing prose.
# Safe for this single-threaded demo (one question processed at a time).
_last_call = {"tool": None, "data": None}


@beta_tool
def scan_tax_loss_harvesting_opportunities(threshold_pct: float = 10.0) -> str:
    """Find positions with an unrealized loss beyond threshold_pct (a tax-loss
    harvesting candidate), joining custodian market values/cost basis to the
    household roll-up.

    Args:
        threshold_pct: Minimum unrealized loss, as a positive percent (e.g. 10
            means flag any position down 10% or more from cost basis).
    """
    result = tlh_scan(threshold_pct)
    _last_call["tool"] = "tlh"
    _last_call["data"] = result
    return json.dumps(result)


@beta_tool
def scan_concentration_risk(threshold_pct: float = 20.0) -> str:
    """Find households where a single position makes up more than
    threshold_pct of the household's total portfolio value, summed across
    every account in that household.

    Args:
        threshold_pct: Minimum household-level position weight, as a percent
            (e.g. 20 means flag any position that is 20% or more of the
            household's total value).
    """
    result = concentration_scan(threshold_pct)
    _last_call["tool"] = "concentration"
    _last_call["data"] = result
    return json.dumps(result)


@beta_tool
def scan_wash_sale_conflicts(threshold_pct: float = 10.0, as_of_date: str = "") -> str:
    """Find tax-loss harvesting candidates that would trigger a wash sale if
    harvested now, because the same security was bought within the trailing
    30 days in ANY account in the household -- including a spouse's account
    or an IRA/Roth, which the IRS attributes together for wash-sale purposes
    even though they're separate accounts and separate 1099s.

    Args:
        threshold_pct: Minimum unrealized loss, as a positive percent, to be
            considered a harvesting candidate (same meaning as in the TLH scan).
        as_of_date: ISO date (YYYY-MM-DD) to treat as "today" for the 30-day
            lookback. Leave blank to use the current date; pass an explicit
            date to reproduce results against this demo's fixed transaction
            dates (e.g. "2026-08-10").
    """
    result = wash_sale_scan(threshold_pct, as_of_date or None)
    _last_call["tool"] = "wash_sale"
    _last_call["data"] = result
    return json.dumps(result)


TOOLS = [
    scan_tax_loss_harvesting_opportunities,
    scan_concentration_risk,
    scan_wash_sale_conflicts,
]

CHART_SYSTEM_PROMPT = """\
You turn a raw scan result (a JSON list of records) into a chart specification. \
Look at the actual field names and values present -- don't assume a fixed shape. \
Pick the fields that best let a reader compare/rank the flagged items at a glance. \
If the data has nothing worth charting (empty, or a single number with no \
comparison), set should_chart to false rather than forcing a chart.

label_fields must, together, uniquely identify every record -- check this before \
answering. If two records would produce the same label (e.g. two rows share the \
same household but hold different positions), add another field to disambiguate \
them (e.g. also include the position/symbol, or the account). Rows that collapse \
onto the same label will visually overlap into a single bar, which is wrong."""


def _propose_chart(question: str, data: list[dict], client: anthropic.Anthropic) -> ChartSpec | None:
    if not data:
        return None
    try:
        response = client.messages.parse(
            model=MODEL,
            max_tokens=1024,
            system=CHART_SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"Original question: {question}\n\n"
                        f"Scan result (JSON):\n{json.dumps(data)}"
                    ),
                }
            ],
            output_format=ChartSpec,
        )
        return response.parsed_output
    except Exception:  # noqa: BLE001 -- charting is a nice-to-have, never break the answer
        return None


def ask(question: str, client: anthropic.Anthropic | None = None) -> dict:
    """Run one question through the agent.

    Returns {"text": str, "tool": ..., "data": [...], "chart_spec": ChartSpec | None}.
    The chart spec is derived by having the model look at the actual scan
    result and decide what's worth plotting and how -- it is not a hardcoded
    template keyed on which tool ran, so a new skill's output still charts
    sensibly without touching the UI layer.
    """
    client = client or anthropic.Anthropic()
    _last_call["tool"] = None
    _last_call["data"] = None

    runner = client.beta.messages.tool_runner(
        model=MODEL,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        tools=TOOLS,
        messages=[{"role": "user", "content": question}],
    )

    final_message = None
    for message in runner:
        final_message = message

    text = "No response."
    if final_message is not None:
        text = "".join(
            block.text for block in final_message.content if block.type == "text"
        )

    data = _last_call["data"]
    chart_spec = _propose_chart(question, data, client) if data else None

    return {
        "text": text,
        "tool": _last_call["tool"],
        "data": data,
        "chart_spec": chart_spec,
    }


if __name__ == "__main__":
    import sys

    q = " ".join(sys.argv[1:]) or "Which households are over-concentrated in a single position?"
    print(f"Q: {q}\n")
    result = ask(q)
    print(result["text"])
    print("\n--- chart spec ---")
    print(result["chart_spec"])
