"""
Streamlit chat UI for the wealth-ops agent demo.

Run with:
    export ANTHROPIC_API_KEY=sk-ant-...
    streamlit run app.py

Optional access controls (both off by default for local dev; set at least
APP_PASSWORD before deploying somewhere public, since every question spends
your Anthropic API credits):
    export APP_PASSWORD=some-shared-code   # gates the whole app behind a code
On Streamlit Community Cloud, set these under Settings -> Secrets instead of
as shell exports -- they're injected as env vars automatically.
"""

import os

import altair as alt
import pandas as pd
import streamlit as st

from agent import ask

st.set_page_config(page_title="Wealth Ops Agent", layout="centered")

MAX_QUESTIONS_PER_SESSION = 20


def _get_app_password() -> str | None:
    try:
        return st.secrets["APP_PASSWORD"]
    except Exception:  # noqa: BLE001 -- st.secrets raises if no secrets.toml exists at all
        return os.environ.get("APP_PASSWORD")


def _check_access() -> bool:
    """Gate the whole app behind a shared access code. Returns True once
    access is granted; renders the entry screen and returns False otherwise.
    If no APP_PASSWORD is configured, the gate is skipped (local dev)."""
    password = _get_app_password()
    if not password:
        return True
    if st.session_state.get("authenticated"):
        return True

    st.title("Wealth Ops Agent")
    st.caption("This demo is access-gated to control API usage. Enter the access code to continue.")
    entered = st.text_input("Access code", type="password")
    if st.button("Enter"):
        if entered == password:
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Incorrect access code.")
    return False


if not _check_access():
    st.stop()

st.title("Wealth Ops Agent")
st.caption(
    "Ask questions over the firm's book of business. Answers are computed from "
    "custodian + portfolio-accounting exports, not generated by the model — "
    "every number cites its source system. Charts are derived by the model "
    "from the shape of the actual scan result, not a hardcoded template."
)

EXAMPLES = [
    "Which accounts have a tax-loss harvesting opportunity this week?",
    "Which households are over-concentrated in a single position?",
]

# dataviz skill palette -- light/dark pair for categorical slot 1 (blue) + chrome
_THEME = {
    "light": dict(bar="#2a78d6", grid="#e1e0d9", axis="#c3c2b7", label="#52514e", bg="#fcfcfb", title="#0b0b0b"),
    "dark": dict(bar="#3987e5", grid="#2c2c2a", axis="#383835", label="#c3c2b7", bg="#1a1a19", title="#ffffff"),
}


def _theme_colors() -> dict:
    base = st.get_option("theme.base") or "light"
    return _THEME["dark" if base == "dark" else "light"]


def _dedupe_labels(labels: list[str]) -> list[str]:
    """Guarantee unique y-axis categories even if the model's label_fields
    weren't sufficient to distinguish every row -- otherwise rows sharing a
    label overplot onto the same bar position."""
    seen: dict[str, int] = {}
    out = []
    for label in labels:
        seen[label] = seen.get(label, 0) + 1
        out.append(label if seen[label] == 1 else f"{label} ({seen[label]})")
    return out


def _build_chart(spec, data: list[dict]):
    """Build a chart purely from the model-authored spec + the raw data rows.
    No knowledge of which skill produced the data lives here -- the spec
    already names which fields to use."""
    if spec is None or not spec.get("should_chart") or not data:
        return None
    if spec.get("chart_type") != "bar":
        return None

    colors = _theme_colors()
    label_fields = spec["label_fields"]
    value_field = spec["value_field"]
    value_format = spec.get("value_format", "number")
    use_abs = spec.get("use_absolute_value", False)

    def _format(value: float) -> str:
        if value_format == "percent":
            return f"{value:.1f}%"
        if value_format == "currency":
            return f"${value:,.0f}"
        return f"{value:,.0f}"

    raw_labels, values, displays = [], [], []
    for row in data:
        value = row.get(value_field)
        if value is None:
            continue
        if use_abs:
            value = abs(value)
        raw_labels.append(" · ".join(str(row.get(f, "")) for f in label_fields))
        values.append(value)
        displays.append(_format(value))

    if not raw_labels:
        return None

    df = pd.DataFrame(
        {"label": _dedupe_labels(raw_labels), "value": values, "display": displays}
    )

    bar_height = 34
    chart_height = max(140, bar_height * len(df))

    bars = (
        alt.Chart(df)
        .mark_bar(cornerRadiusEnd=4, height=bar_height - 10, color=colors["bar"])
        .encode(
            x=alt.X("value:Q", title=spec.get("value_axis_title", "Value")),
            y=alt.Y("label:N", title=None, sort="-x"),
            tooltip=[
                alt.Tooltip("label:N", title="Item"),
                alt.Tooltip("display:N", title="Value"),
            ],
        )
    )

    labels = (
        alt.Chart(df)
        .mark_text(align="left", dx=6, color=colors["label"], fontSize=12)
        .encode(
            x=alt.X("value:Q"),
            y=alt.Y("label:N", sort="-x"),
            text="display:N",
        )
    )

    return (
        (bars + labels)
        .properties(title=spec.get("title", ""), height=chart_height, background=colors["bg"])
        .configure_title(color=colors["title"], fontSize=15)
        .configure_axis(
            gridColor=colors["grid"],
            domainColor=colors["axis"],
            tickColor=colors["axis"],
            labelColor=colors["label"],
            labelLimit=320,
            labelFontSize=12,
        )
        .configure_view(strokeWidth=0)
    )


if "messages" not in st.session_state:
    st.session_state.messages = []

with st.sidebar:
    st.subheader("Try asking")
    for example in EXAMPLES:
        if st.button(example, use_container_width=True):
            st.session_state.pending_question = example

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("chart") is not None:
            st.altair_chart(msg["chart"], use_container_width=True)

question = st.chat_input("Ask about the book...")
if "pending_question" in st.session_state:
    question = st.session_state.pop("pending_question")

if question:
    st.session_state.messages.append({"role": "user", "content": question, "chart": None})
    with st.chat_message("user"):
        st.markdown(question)

    asked_so_far = st.session_state.get("question_count", 0)

    with st.chat_message("assistant"):
        if asked_so_far >= MAX_QUESTIONS_PER_SESSION:
            text, chart = (
                f"This demo is capped at {MAX_QUESTIONS_PER_SESSION} questions per "
                "session to control API costs. Refresh the page to start a new session.",
                None,
            )
        else:
            st.session_state.question_count = asked_so_far + 1
            with st.spinner("Scanning custodian + portfolio-accounting data..."):
                try:
                    result = ask(question)
                    spec = result["chart_spec"].model_dump() if result["chart_spec"] else None
                    text, chart = result["text"], _build_chart(spec, result["data"])
                except Exception as e:  # noqa: BLE001
                    text, chart = f"Error: {e}", None
        st.markdown(text)
        if chart is not None:
            st.altair_chart(chart, use_container_width=True)

    st.session_state.messages.append({"role": "assistant", "content": text, "chart": chart})
